// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "List of products",
        "description": "Request all available products",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductsList"
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          }
        }
      },
      "post": {
        "summary": "Create Product",
        "description": "Add a new product to the table",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductPostBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product added successfully",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          },
          "400": {
            "description": "Product data is invalid",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "Product details",
        "description": "Request available product by Id",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "There is product in a table",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "There is no product  in a table",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Stock": {
      "properties": {
        "product_id": {
          "title": "Stock.product_id"
        },
        "count": {
          "title": "Stock.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "Stock",
      "type": "object"
    },
    "AvailableProduct": {
      "allOf": [],
      "title": "AvailableProduct"
    },
    "ProductPostBody": {
      "properties": {
        "title": {
          "title": "ProductPostBody.title",
          "type": "string"
        },
        "description": {
          "title": "ProductPostBody.description",
          "type": "string"
        },
        "price": {
          "title": "ProductPostBody.price",
          "type": "number"
        },
        "count": {
          "title": "ProductPostBody.count",
          "type": "number"
        }
      },
      "required": [
        "title",
        "description",
        "price",
        "count"
      ],
      "additionalProperties": false,
      "title": "ProductPostBody",
      "type": "object"
    },
    "ProductsList": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ProductsList.products.[]"
          },
          "title": "ProductsList.products",
          "type": "array"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "ProductsList",
      "type": "object"
    },
    "InfoResponse": {
      "properties": {
        "message": {
          "title": "InfoResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "InfoResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};